services:
  - type: web
    name: event-manager
    runtime: native
    plan: free
    buildCommand: bash build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
